apiVersion: v1
kind: Pod
metadata:
  name: secure-gateway-pod
  labels:
    tier: infrastructure
spec:
  runtimeClassName: gvisor
  containers:
  - name: hardened-proxy-node
    image: nginx:alpine
    ports:
    - containerPort: 80
    securityContext:
      runAsUser: 101
      runAsGroup: 101
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
